revoke delete on table "public"."user_memory" from "anon";

revoke insert on table "public"."user_memory" from "anon";

revoke references on table "public"."user_memory" from "anon";

revoke select on table "public"."user_memory" from "anon";

revoke trigger on table "public"."user_memory" from "anon";

revoke truncate on table "public"."user_memory" from "anon";

revoke update on table "public"."user_memory" from "anon";

revoke delete on table "public"."user_memory" from "authenticated";

revoke insert on table "public"."user_memory" from "authenticated";

revoke references on table "public"."user_memory" from "authenticated";

revoke select on table "public"."user_memory" from "authenticated";

revoke trigger on table "public"."user_memory" from "authenticated";

revoke truncate on table "public"."user_memory" from "authenticated";

revoke update on table "public"."user_memory" from "authenticated";

revoke delete on table "public"."user_memory" from "service_role";

revoke insert on table "public"."user_memory" from "service_role";

revoke references on table "public"."user_memory" from "service_role";

revoke select on table "public"."user_memory" from "service_role";

revoke trigger on table "public"."user_memory" from "service_role";

revoke truncate on table "public"."user_memory" from "service_role";

revoke update on table "public"."user_memory" from "service_role";

alter table "public"."chat_logs" drop constraint "chat_logs_kb_id_fkey";

alter table "public"."user_memory" drop constraint "user_memory_session_id_key_key";

drop function if exists "public"."match_knowledge_base"(query_embedding public.vector, match_threshold double precision, match_count integer);

alter table "public"."user_memory" drop constraint "user_memory_pkey";

alter table "public"."chat_logs" drop constraint "chat_logs_pkey";

drop index if exists "public"."idx_chat_logs_kb_id";

drop index if exists "public"."user_memory_pkey";

drop index if exists "public"."user_memory_session_id_key_key";

drop index if exists "public"."chat_logs_pkey";

drop table "public"."user_memory";


  create table "public"."chat_logs_kb" (
    "chat_log_kb_id" bigint generated by default as identity not null,
    "chat_id" bigint not null,
    "kb_id" text not null,
    "created_at" timestamp with time zone default now(),
    "similarity" double precision
      );


alter table "public"."chat_logs_kb" enable row level security;

alter table "public"."chat_logs" drop column "id";

alter table "public"."chat_logs" drop column "kb_id";

alter table "public"."chat_logs" add column "chat_id" bigint generated by default as identity not null;

alter table "public"."knowledge_base" drop column "tema";

alter table "public"."knowledge_base" add column "eixo_tematico" text;

alter table "public"."knowledge_base" add column "kb_count" numeric;

alter table "public"."knowledge_base" add column "tags" text[];

alter table "public"."knowledge_base" add column "topico" text;

alter table "public"."knowledge_base" alter column "descricao" set not null;

alter table "public"."sessions" add column "id" bigint generated by default as identity not null;

CREATE UNIQUE INDEX chat_log_kb_chat_log_kb_id_key ON public.chat_logs_kb USING btree (chat_log_kb_id);

CREATE UNIQUE INDEX chat_log_kb_pkey ON public.chat_logs_kb USING btree (chat_log_kb_id);

CREATE INDEX idx_chat_logs_kb_log ON public.chat_logs_kb USING btree (chat_log_kb_id);

CREATE INDEX idx_kb_eixo ON public.knowledge_base USING btree (eixo_tematico);

CREATE INDEX idx_kb_embedding ON public.knowledge_base USING hnsw (embedding public.vector_cosine_ops);

CREATE INDEX idx_kb_topico ON public.knowledge_base USING btree (topico);

CREATE UNIQUE INDEX sessions_id_key ON public.sessions USING btree (id);

CREATE UNIQUE INDEX chat_logs_pkey ON public.chat_logs USING btree (chat_id);

alter table "public"."chat_logs_kb" add constraint "chat_log_kb_pkey" PRIMARY KEY using index "chat_log_kb_pkey";

alter table "public"."chat_logs" add constraint "chat_logs_pkey" PRIMARY KEY using index "chat_logs_pkey";

alter table "public"."chat_logs_kb" add constraint "chat_log_kb_chat_id_fkey" FOREIGN KEY (chat_id) REFERENCES public.chat_logs(chat_id) ON UPDATE CASCADE not valid;

alter table "public"."chat_logs_kb" validate constraint "chat_log_kb_chat_id_fkey";

alter table "public"."chat_logs_kb" add constraint "chat_log_kb_chat_log_kb_id_key" UNIQUE using index "chat_log_kb_chat_log_kb_id_key";

alter table "public"."chat_logs_kb" add constraint "chat_log_kb_kb_id_fkey" FOREIGN KEY (kb_id) REFERENCES public.knowledge_base(kb_id) ON UPDATE CASCADE not valid;

alter table "public"."chat_logs_kb" validate constraint "chat_log_kb_kb_id_fkey";

alter table "public"."sessions" add constraint "sessions_id_key" UNIQUE using index "sessions_id_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.match_knowledge_base(query_embedding public.vector, match_threshold double precision, match_count integer, filter_topic text DEFAULT NULL::text)
 RETURNS TABLE(id text, topico text, eixo_tematico text, descricao text, similarity double precision)
 LANGUAGE plpgsql
AS $function$
  BEGIN
    return query
    select
      knowledge_base.kb_id,
      knowledge_base.topico,
      knowledge_base.eixo_tematico,
      knowledge_base.descricao,
      1 - (knowledge_base.embedding <=> query_embedding) as similarity
    from knowledge_base
    where 1 - (knowledge_base.embedding <=> query_embedding) > match_threshold
    and (filter_topic is null or knowledge_base.topico = filter_topic)
    order by knowledge_base.embedding <=> query_embedding
    limit match_count;
  END;
  $function$
;

grant delete on table "public"."chat_logs_kb" to "anon";

grant insert on table "public"."chat_logs_kb" to "anon";

grant references on table "public"."chat_logs_kb" to "anon";

grant select on table "public"."chat_logs_kb" to "anon";

grant trigger on table "public"."chat_logs_kb" to "anon";

grant truncate on table "public"."chat_logs_kb" to "anon";

grant update on table "public"."chat_logs_kb" to "anon";

grant delete on table "public"."chat_logs_kb" to "authenticated";

grant insert on table "public"."chat_logs_kb" to "authenticated";

grant references on table "public"."chat_logs_kb" to "authenticated";

grant select on table "public"."chat_logs_kb" to "authenticated";

grant trigger on table "public"."chat_logs_kb" to "authenticated";

grant truncate on table "public"."chat_logs_kb" to "authenticated";

grant update on table "public"."chat_logs_kb" to "authenticated";

grant delete on table "public"."chat_logs_kb" to "service_role";

grant insert on table "public"."chat_logs_kb" to "service_role";

grant references on table "public"."chat_logs_kb" to "service_role";

grant select on table "public"."chat_logs_kb" to "service_role";

grant trigger on table "public"."chat_logs_kb" to "service_role";

grant truncate on table "public"."chat_logs_kb" to "service_role";

grant update on table "public"."chat_logs_kb" to "service_role";


