alter table "public"."sessions" add column "id" bigint generated by default as identity not null;

CREATE UNIQUE INDEX sessions_id_key ON public.sessions USING btree (id);

alter table "public"."sessions" add constraint "sessions_id_key" UNIQUE using index "sessions_id_key";


